/*
 * Copyright (c) 2020 Sekhar Bhattacharya
 *
 * SPDS-License-Identifier: MIT
 */

#ifndef _ARM_PL011_IF_H_
#define _ARM_PL011_IF_H_

#define MMIO_READ_32(base, reg)        (*((uint32_t*)((base) + (reg))))
#define MMIO_READ_64(base, reg)        (*((uint64_t*)((base) + (reg))))
#define MMIO_WRITE_32(base, reg, val)  (*((uint32_t*)((base) + (reg))) = (val))
#define MMIO_WRITE_64(base, reg, val)  (*((uint64_t*)((base) + (reg))) = (val))

#define UARTDR                         (0x000)
#define G_UARTDR_ANYERR(r)             (((r) >> 8) & 0xf)
#define G_UARTDR_OE(r)                 (((r) >> 11) & 1)
#define G_UARTDR_BE(r)                 (((r) >> 10) & 1)
#define G_UARTDR_PE(r)                 (((r) >> 9) & 1)
#define G_UARTDR_FE(r)                 (((r) >> 8) & 1)
#define G_UARTDR_DATA(r)               ((r) & 0xff)
#define F_UARTDR_DATA(f)               ((f) & 0xff)
#define uartdr_read(b)                 (MMIO_READ_32(b, UARTDR))
#define uartdr_write(b, r)             (MMIO_WRITE_32(b, UARTDR, r))

#define UARTRSR                        (0x004)
#define UARTECR                        (0x004)
#define G_UARTRSR_OE(r)                (((r) >> 3) & 1)
#define G_UARTRSR_BE(r)                (((r) >> 2) & 1)
#define G_UARTRSR_PE(r)                (((r) >> 1) & 1)
#define G_UARTRSR_FE(r)                ((r) & 1)
#define uartrsr_read(b)                (MMIO_READ_32(b, UARTRSR))
#define uartecr_write(b, r)            (MMIO_WRITE_32(b, UARTECR, r))

#define UARTFR                         (0x018)
#define G_UARTFR_RI(r)                 (((r) >> 8) & 1)
#define G_UARTFR_TXFE(r)               (((r) >> 7) & 1)
#define G_UARTFR_RXFF(r)               (((r) >> 6) & 1)
#define G_UARTFR_TXFF(r)               (((r) >> 5) & 1)
#define G_UARTFR_RXFE(r)               (((r) >> 4) & 1)
#define G_UARTFR_BUSY(r)               (((r) >> 3) & 1)
#define G_UARTFR_DCD(r)                (((r) >> 2) & 1)
#define G_UARTFR_DSR(r)                (((r) >> 1) & 1)
#define G_UARTFR_CTS(r)                ((r) & 1)
#define uartfr_read(b)                 (MMIO_READ_32(b, UARTFR))

#define UARTILPR                       (0x020)
#define G_UARTILPR_ILPDVSR(r)          ((r) & 0xff)
#define F_UARTILPR_ILPDVSR(f)          ((f) & 0xff)
#define uartilpr_read(b)               (MMIO_READ_32(b, UARTILPR))
#define uartilpr_write(b, r)           (MMIO_WRITE_32(b, UARTILPR, r))

#define UARTIBRD                       (0x024)
#define G_UARTIBRD_BAUD_DIVINT(r)      ((r) & 0xff)
#define F_UARTIBRD_BAUD_DIVINT(f)      ((f) & 0xff)
#define uartibrd_read(b)               (MMIO_READ_32(b, UARTIBRD))
#define uartibrd_write(b, r)           (MMIO_WRITE_32(b, UARTIBRD, r))

#define UARTFBRD                       (0x028)
#define G_UARTFBRD_BAUD_DIVFRAC(r)     ((r) & 0x3f)
#define F_UARTFBRD_BAUD_DIVFRAC(f)     ((f) & 0x3f)
#define uartfbrd_read(b)               (MMIO_READ_32(b, UARTFBRD))
#define uartfbrd_write(b, r)           (MMIO_WRITE_32(b, UARTFBRD, r))

#define UARTLCR_H                      (0x02C)
#define G_UARTLCR_H_SPS(r)             (((r) >> 7) & 1)
#define G_UARTLCR_H_WLEN(r)            (((r) >> 5) & 3)
#define G_UARTLCR_H_FEN(r)             (((r) >> 4) & 1)
#define G_UARTLCR_H_STP2(r)            (((r) >> 3) & 1)
#define G_UARTLCR_H_EPS(r)             (((r) >> 2) & 1)
#define G_UARTLCR_H_PEN(r)             (((r) >> 1) & 1)
#define S_UARTLCR_H_SPS                (1 << 7)
#define F_UARTLCR_H_WLEN(f)            (((f) & 3) << 5)
#define S_UARTLCR_H_FEN                (1 << 4)
#define S_UARTLCR_H_STP2               (1 << 3)
#define S_UARTLCR_H_EPS                (1 << 2)
#define S_UARTLCR_H_PEN                (1 << 1)
#define S_UARTLCR_H_BRK                (1)
#define uartlcr_h_read(b)              (MMIO_READ_32(b, UARTLCR_H))
#define uartlcr_h_write(b, r)          (MMIO_WRITE_32(b, UARTLCR_H, r))

#define UARTCR                         (0x030)
#define G_UARTCR_CTSEN(r)              (((r) >> 15) & 1)
#define G_UARTCR_RTSEN(r)              (((r) >> 14) & 1)
#define G_UARTCR_OUT2(r)               (((r) >> 13) & 1)
#define G_UARTCR_OUT1(r)               (((r) >> 12) & 1)
#define G_UARTCR_RTS(r)                (((r) >> 11) & 1)
#define G_UARTCR_DTR(r)                (((r) >> 10) & 1)
#define G_UARTCR_RXE(r)                (((r) >> 9) & 1)
#define G_UARTCR_TXE(r)                (((r) >> 8) & 1)
#define G_UARTCR_LBE(r)                (((r) >> 7) & 1)
#define G_UARTCR_SIRLP(r)              (((r) >> 2) & 1)
#define G_UARTCR_SIREN(r)              (((r) >> 1) & 1)
#define G_UARTCR_UARTEN(r)             ((r) & 1)
#define S_UARTCR_CTSEN                 (1 << 15)
#define S_UARTCR_RTSEN                 (1 << 14)
#define S_UARTCR_OUT2                  (1 << 13)
#define S_UARTCR_OUT1                  (1 << 12)
#define S_UARTCR_RTS                   (1 << 11)
#define S_UARTCR_DTR                   (1 << 10)
#define S_UARTCR_RXE                   (1 << 9)
#define S_UARTCR_TXE                   (1 << 8)
#define S_UARTCR_LBE                   (1 << 7)
#define S_UARTCR_SIRLP                 (1 << 2)
#define S_UARTCR_SIREN                 (1 << 1)
#define S_UARTCR_UARTEN                (1)
#define uartcr_read(b)                 (MMIO_READ_32(b, UARTCR))
#define uartcr_write(b, r)             (MMIO_WRITE_32(b, UARTCR, r))

#define UARTIFLS                       (0x034)
#define G_UARTIFLS_RXIFLSEL(r)         (((r) >> 3) & 7)
#define G_UARTIFLS_TXIFLSEL(r)         ((r) & 7)
#define uartifls_read(b)               (MMIO_READ_32(b, UARTIFLS))
#define uartifls_write(b, r)           (MMIO_WRITE_32(b, UARTIFLS, r))

#define UARTIMSC                       (0x038)
#define G_UARTIMSC_OEIM(r)             (((r) >> 10) & 1)
#define G_UARTIMSC_BEIM(r)             (((r) >> 9) & 1)
#define G_UARTIMSC_PEIM(r)             (((r) >> 8) & 1)
#define G_UARTIMSC_FEIM(r)             (((r) >> 7) & 1)
#define G_UARTIMSC_RTIM(r)             (((r) >> 6) & 1)
#define G_UARTIMSC_TXIM(r)             (((r) >> 5) & 1)
#define G_UARTIMSC_RXIM(r)             (((r) >> 4) & 1)
#define G_UARTIMSC_DSRMIM(r)           (((r) >> 3) & 1)
#define G_UARTIMSC_DCDMIM(r)           (((r) >> 2) & 1)
#define G_UARTIMSC_CTSMIM(r)           (((r) >> 1) & 1)
#define G_UARTIMSC_RIMIM(r)            ((r) & 1)
#define S_UARTIMSC_OEIM                (1 << 10)
#define S_UARTIMSC_BEIM                (1 << 9)
#define S_UARTIMSC_PEIM                (1 << 8)
#define S_UARTIMSC_FEIM                (1 << 7)
#define S_UARTIMSC_RTIM                (1 << 6)
#define S_UARTIMSC_TXIM                (1 << 5)
#define S_UARTIMSC_RXIM                (1 << 4)
#define S_UARTIMSC_DSRMIM              (1 << 3)
#define S_UARTIMSC_DCDMIM              (1 << 2)
#define S_UARTIMSC_CTSMIM              (1 << 1)
#define S_UARTIMSC_RIMIM               (1)
#define uartimsc_read(b)               (MMIO_READ_32(b, UARTIMSC))
#define uartimsc_write(b, r)           (MMIO_WRITE_32(b, UARTIMSC, r))

#define UARTRIS                        (0x03C)
#define G_UARTRIS_OEIS(r)              (((r) >> 10) & 1)
#define G_UARTRIS_BEIS(r)              (((r) >> 9) & 1)
#define G_UARTRIS_PEIS(r)              (((r) >> 8) & 1)
#define G_UARTRIS_FEIS(r)              (((r) >> 7) & 1)
#define G_UARTRIS_RTIS(r)              (((r) >> 6) & 1)
#define G_UARTRIS_TXIS(r)              (((r) >> 5) & 1)
#define G_UARTRIS_RXIS(r)              (((r) >> 4) & 1)
#define G_UARTRIS_DSRMIS(r)            (((r) >> 3) & 1)
#define G_UARTRIS_DCDMIS(r)            (((r) >> 2) & 1)
#define G_UARTRIS_CTSMIS(r)            (((r) >> 1) & 1)
#define G_UARTRIS_RIMIS(r)             ((r) & 1)
#define uartris_read(b)                (MMIO_READ_32(b, UARTRIS))

#define UARTMIS                        (0x040)
#define G_UARTMIS_OEMIS(r)             (((r) >> 10) & 1)
#define G_UARTMIS_BEMIS(r)             (((r) >> 9) & 1)
#define G_UARTMIS_PEMIS(r)             (((r) >> 8) & 1)
#define G_UARTMIS_FEMIS(r)             (((r) >> 7) & 1)
#define G_UARTMIS_RTMIS(r)             (((r) >> 6) & 1)
#define G_UARTMIS_TXMIS(r)             (((r) >> 5) & 1)
#define G_UARTMIS_RXMIS(r)             (((r) >> 4) & 1)
#define G_UARTMIS_DSRMMIS(r)           (((r) >> 3) & 1)
#define G_UARTMIS_DCDMMIS(r)           (((r) >> 2) & 1)
#define G_UARTMIS_CTSMMIS(r)           (((r) >> 1) & 1)
#define G_UARTMIS_RIMMIS(r)            ((r) & 1)
#define uartmis_read(b)                (MMIO_READ_32(b, UARTMIS))

#define UARTICR                        (0x044)
#define S_UARTICR_OEIC                 (1 << 10)
#define S_UARTICR_BEIC                 (1 << 9)
#define S_UARTICR_PEIC                 (1 << 8)
#define S_UARTICR_FEIC                 (1 << 7)
#define S_UARTICR_RTIC                 (1 << 6)
#define S_UARTICR_TXIC                 (1 << 5)
#define S_UARTICR_RXIC                 (1 << 4)
#define S_UARTICR_DSRMIC               (1 << 3)
#define S_UARTICR_DCDMIC               (1 << 2)
#define S_UARTICR_CTSMIC               (1 << 1)
#define S_UARTICR_RIMIC                (1)
#define uarticr_write(b, r)            (MMIO_WRITE_32(b, UARTICR, r))

#define UARTDMACR                      (0x048)
#define G_UARTDMACR_DMAONERR(r)        (((r) >> 2) & 1)
#define G_UARTDMACR_TXDMAE(r)          (((r) >> 1) & 1)
#define G_UARTDMACR_RXDMAE(r)          ((r) & 1)
#define F_UARTDMACR_DMAONERR(f)        (((f) & 1) << 2)
#define S_UARTDMACR_TXDMAE             (1 << 1)
#define S_UARTDMACR_RXDMAE             (1)
#define uartdmacr_read(b)              (MMIO_READ_32(b, UARTDMACR))
#define uartdmacr_write(b, r)          (MMIO_WRITE_32(b, UARTDMACR, r))

#define UARTPERIPHID0                  (0xFE0)
#define uartperiphid0_read(b)          (MMIO_READ_32(b, UARTPERIPHID0))

#define UARTPERIPHID1                  (0xFE4)
#define uartperiphid1_read(b)          (MMIO_READ_32(b, UARTPERIPHID1))

#define UARTPERIPHID2                  (0xFE8)
#define uartperiphid2_read(b)          (MMIO_READ_32(b, UARTPERIPHID2))

#define UARTPERIPHID3                  (0xFEC)
#define uartperiphid3_read(b)          (MMIO_READ_32(b, UARTPERIPHID3))

#define UARTPCELLID0                   (0xFF0)
#define uartpcellid0_read(b)           (MMIO_READ_32(b, UARTPCELLID0))

#define UARTPCELLID1                   (0xFF4)
#define uartpcellid1_read(b)           (MMIO_READ_32(b, UARTPCELLID1))

#define UARTPCELLID2                   (0xFF8)
#define uartpcellid2_read(b)           (MMIO_READ_32(b, UARTPCELLID2))

#define UARTPCELLID3                   (0xFFC)
#define uartpcellid3_read(b)           (MMIO_READ_32(b, UARTPCELLID3))

#endif // _ARM_PL011_IF_H_
