#ifndef __PLATFORM_IOMEM_H__
#define __PLATFORM_IOMEM_H__

// UART0
// TODO: VBASE SHOULDN'T BE HARDCODED!
#define R_UART0_PBASE (0x44E09000)
#define R_UART0_VBASE (0xFFFF0000)

#define O_UART0_THR (0x0)
#define R_UART0_THR (R_UART0_VBASE+O_UART0_THR)

#define O_UART0_RHR (0x0)
#define R_UART0_RHR (R_UART0_VBASE+O_UART0_RHR)

#define O_UART0_SSR (0x44)
#define R_UART0_SSR (R_UART0_VBASE+O_UART0_SSR)

#endif // __PLATFORM_IOMEM_H__

