#!/bin/bash

QEMU=qemu-system-arm
KERNELIMG="../kernel.img"
QMEM="512M"
QOPTIONS="-serial stdio"
QPLATFORM="-M realview-pb-a8"
QCPU="cortex-a8"
QGDB="-s -S"

while test $# -gt 0
do
  if [[ $1 == "-p" ]]
  then
    shift
    if [[ $# -gt 0 && $1 != "-nogdb" ]]
    then
      if [[ $1 == "versatilepb" || $1 == "realview-pb-a8" ]]
      then
        QPLATFORM="-M $1"
        if [[ $1 == "versatilepb" ]]
        then
          QOPTIONS="-cpu ${QCPU} ${QOPTIONS}"
          QMEM="128M"
        fi
      else
        echo "Usage: $0 [-p <system_emulator>] [-nogdb]"
        printf "Platforms supported:\nversatilepb\nrealview-pb-a8\n"
        exit
      fi
    else
      echo "Usage: $0 [-p <system_emulator>] [-nogdb]"
      exit
    fi
  else
    if [[ $1 == "-nogdb" ]]
    then
      QGDB=""
    fi
  fi
  shift
done

if [[ -n $QGDB ]]
then
  echo "Running QEMU in GDB mode"
fi

QOPTIONS="-m ${QMEM} ${QOPTIONS}"

echo "Platform: ${QPLATFORM#-M }"
echo "CPU: ${QCPU}"
echo "MEM: ${QMEM}"

# QEMU is able to emulate the RealView Platform Baseboard with a Cortex-A8 CPU
$QEMU $QPLATFORM $QOPTIONS $QGDB -kernel $KERNELIMG
